### ISSUE TITLE
Please add Apache Drill JDBC driver

### ISSUE THREAD

**Issue by amalic** [chrdebru/r2rml#1]
```
<dependency>
    <groupId>org.apache.drill.exec</groupId>
    <artifactId>drill-jdbc</artifactId>
    <version>1.13.0</version>
</dependency>
```

**Comment by chrdebru** [comment]
I will look into that. From a first glance, it seems that there are version conflicts in the artefacts (both version 1.13.0 and 1.12.0.

**Comment by amalic** [comment]
I have it running in my fork. So far I have not discovered any issues. I ran it with postgres and apache-drill.

 I removed Oracle and reorganized the project structure. I also had to change the build because of apache drill not finding a config file. If you want I can do a pull request.

**Comment by chrdebru** [comment]
Sure. I'll see whether the Oracle library poses a problem, we use it for our projects.

**Comment by amalic** [comment]
check this out:
https://mvnrepository.com/artifact/oracle/ojdbc6/11.2.0.3
